// This file is auto-generated by scripts/sync-skiller-abi.js
export const ABIS = {
  SkillerProfile: [
    {
      "inputs": [],
      "name": "totalSupply",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "tokenByIndex",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    // ... (rest of the file is large, so I will check it first before writing to it blindly or I might overwrite the whole file with just this snippet which is bad)
  ]
} as const;

